# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7cc84822068d7e0cd087237bf7b20ce837ef7ca35214153af5f28d8969c73889f781103908d1617f160d5fbb890a6d0bba93f653863cd2f8a87fc67f61380f

test:
  secret_key_base: e5a272dfa0aad604d1e2ec0eed57adcd6672501395101daf82f943591e410726c1090b28d278b0d4aca41b686b176dc3a8bc34018f8e352f412abea15ef3352e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
